# Instana Agent Config
instana_host: "ingress.your-instana-domain.com"   
instana_key: "YOUR_AGENT_KEY"                     
instana_port: 443                                

# RPM File Path
instana_rpm_path: "/root/instanasw/instana-agent-static-j9-20251007-1723.x86_64.rpm"

# service name
service_name: "instana-agent"                     