# playbooks/deploy_instana.yml
---
- name: 部署 Instana Agent 三步流程
  hosts: instana_agents
  become: yes  # 第一步：执行 sudo su - 获取 root 权限
  
  tasks:
    # 第二步：在目标机器 /root 下创建 instana-agent 文件夹
    - name: 创建安装目录
      file:
        path: /root/instana-agent
        state: directory
        owner: root
        group: root
        mode: '0700'
    
    # 第三步：复制 RPM 文件到 /root/instana-agent 文件夹
    - name: 复制 RPM 文件
      copy:
        src: "{{ instana_rpm_path }}"
        dest: /root/instana-agent/
        mode: '0644'