# playbooks/deploy_instana.yml
---
- name: Deploy Instana Linux Agent
  hosts: instana_agents
  become: yes  # sudo su - get root access
  
  tasks:
    # Create instana-agent folder under /root on target host
    - name: Create agent folder
      file:
        path: /root/instana-agent
        state: directory
        owner: root
        group: root
        mode: '0700'
    
    # Copy Instana agent RPM to /root/instana-agent 
    - name: Copy agent RPM file
      copy:
        src: "{{ instana_rpm_path }}"
        dest: /root/instana-agent/
        mode: '0644'

    # Install Instana agent 
    - name: Install Instana Agent
      command: rpm -ivh /root/instana-agent/instana-agent-static-j9-20251007-1723.x86_64.rpm
      register: install_result
      ignore_errors: yes  

    # Backup Config file
    - name: Backup Config file
      command: >
        mv /opt/instana/agent/etc/instana/com.instana.agent.main.sender.Backend.cfg
        /opt/instana/agent/etc/instana/com.instana.agent.main.sender.Backend.cfg.bak
      args:
        creates: /opt/instana/agent/etc/instana/com.instana.agent.main.sender.Backend.cfg.bak
        
    # Copy config file
    - name: Copy config file
      copy:
        src: /root/instanasw/com.instana.agent.main.sender.Backend.cfg
        dest: /opt/instana/agent/etc/instana/com.instana.agent.main.sender.Backend.cfg
        owner: root
        group: root
        mode: '0600'
      notify: restart instana-agent

    # Backup zone Config file
    - name: Backup zone Config file
      command: >
        mv /opt/instana/agent/etc/instana/configuration.yaml
        /opt/instana/agent/etc/instana/configuration.yaml.bak
      args:
        creates: /opt/instana/agent/etc/instana/configuration.yaml.bak
        
    # Copy zone config file
    - name: Copy zone config file
      copy:
        src: /root/instanasw/configuration.yaml
        dest: /opt/instana/agent/etc/instana/configuration.yaml
        owner: root
        group: root
        mode: '0600'
      notify: restart instana-agent
        
  handlers:
    # restart instana-agent service
    - name: restart instana-agent
      systemd:
        name: instana-agent
        state: restarted
        daemon_reload: yes